name: New Software Package Request
description: Request additional Software Package to be installed in E4S stack
title: "[software]: "
labels: [software]
assignees:
  - shahzebsiddiqui
  - etpalmer63
  - jscook2345
body:
  - type: textarea
    id: Description
    attributes:
      label: Request Description
      description: Please specify the spack package you would like to install. You may run **spack list** or see [https://spack.readthedocs.io/en/latest/package_list.html](https://spack.readthedocs.io/en/latest/package_list.html) for list of available packages. Please specify any variants alongwith any compiler preference. You can run **spack info** to see more details regarding a spack package.  
    validations:
      required: true
  - type: dropdown
    id: NERSC_ticket
    attributes:
      label: Do you have a NERSC user ticket related to this request?
      description: Check [https://help.nersc.gov](https://help.nersc.gov)
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
        required: true
  - type: textarea
    id: Ticket_Number
    attributes:
      label: If you have a NERSC user ticket, please specify the ticket number
    validations:
      required: false
